### ISSUE TITLE
Runtime Error: Received 403 Access forbidden

### ISSUE THREAD

**Issue by dgurazada** [duosecurity/duo_python#19]
admin_api.get_admins() giving me 403 forbidden error.I'm using AdminAPI credentials.

**Comment by BradleyHiggins** [comment]
In the Duo Admin Panel, your Admin API application settings must enable the 'Grant Administrators' permission in order to make this API call.  Please contact support@duo.com for any further assistance on this issue - they're able to dig into your specific account details to help diagnose what's going on.

Thanks for using Duo!
